---
categories:
- stream-of-consciousness
date: 2023-12-12
date-modified: 2025-09-26
publish: true
title: Lack of Structure
---

Just dumping thoughts on a piece of text helps me get to know myself better and understand what's inside. My systems should reflect this understanding.

It is already hard enough to begin. Simplify it and accept that lack of structure is natural. It’s human nature, my nature. Write and see how well things connect, how effectively I generate ideas, and how I improve.

"Should I just write here?" he asks for the hundredth time. The answer has been discussed and decided upon. It's clear. But there's a lingering shadow and dust that obscure the clarity of this decision.

He had to make many decisions, and being here is the result of a chain of choices. He couldn’t have chosen a better path, because a better path only exists when all factors are considered. And he has no way of knowing if that’s true.

"But why should I go on?" he adds. Because going forward is what shapes you. An endpoint and future may not exist; forget about them. There's no proof of the existence of past or future, so don’t take their reality for granted.

Only the act of moving forward matters. And this movement lacks structure. Adding complexity results in escaping the present moment. But the moment should always be there—sometimes altered, sometimes cohesive.
