---
categories:
- essay
date: 2024-07-22
date-modified: 2025-09-26
publish: true
title: On the fragility of claims
---

AG1, Andrew Huberman, more of the same?

After watching following video [YouTube](https://m.youtube.com/watch?v=wb1g-Cbcjwo) I couldn't stop thinking how easily we can get lied to. It's not that I'm arguing they are blatantly lying about AG1 efficacy. It's that we can get lured by claims so easily.. just because they are wrapped in a neat packaging and overly sprinkled by trendy qualifiers we stop doubting the claims that are made.

Are they even meaningful claims? Are they even worth anything? Or are they just more of the same, a candy bar.

It's not that people that I think are knowledgeable lie. It's that every claim is fragile without the necessary critical thinking backing it up. It must happen in my mind - and only there, an unavoidable step to achieve truth; science.

How easily can we fall victim from people, who _maybe_ not even want to do that. It's not _only_ their fault; it's from the lazy actuation of my critical senses.

Is it fair to demand this capability from everyone? A good question. Probably not.
